server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "ncba.local"
    data_dir = "/opt/spire/data/server"
    log_level = "DEBUG"
    ca_ttl = "24h"
    default_x509_svid_ttl = "1h"
    default_jwt_svid_ttl = "5m"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "postgres"
            connection_string = "host=postgres port=5432 user=ncba password=ncba_secret dbname=ncba sslmode=disable"
        }
    }
    KeyManager "disk" {
        plugin_data {
            keys_path = "/opt/spire/data/server/keys.json"
        }
    }
    NodeAttestor "join_token" {
        plugin_data {}
    }
}
